add_requires("glfw3webgpu v1.3.0-alpha")

target("fei-graphics-webgpu-glfw")
    set_kind("static")
    add_rules("fei.reflect")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-graphics-webgpu", "fei-shader-webgpu", "fei-window")
    add_packages("glfw", "wgpu-native", "glfw3webgpu")

target("fei-graphics-webgpu-glfw-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-graphics-webgpu-glfw")
