add_requires("glfw3webgpu v1.3.0-alpha")

target("entisium-graphics-webgpu-glfw")
    set_kind("static")
    add_rules("entisium.reflect")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-graphics", "entisium-graphics-webgpu", "entisium-shader-webgpu", "entisium-window-glfw")
    add_packages("glfw", "wgpu-native", "glfw3webgpu")

target("entisium-graphics-webgpu-glfw-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-graphics-webgpu-glfw")
