target("entisium-devtools-input")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp", "src/*.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-devtools", "entisium-input")

target("entisium-devtools-input-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_includedirs("src")
    add_deps("entisium-devtools-input")
