target("fei-devtools-input")
    set_kind("static")
    add_headerfiles("include/**.hpp", "src/*.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-devtools", "fei-window")
    add_packages("nlohmann_json")

target("fei-devtools-input-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_includedirs("src")
    add_deps("fei-devtools-input")
