target("entisium-imgui")
    set_kind("static")
    add_rules("entisium.reflect")
    add_shader_source("imgui", path.join(os.scriptdir(), "shaders"))
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base", "entisium-refl", "entisium-ecs", "entisium-app", "entisium-math", "entisium-asset", "entisium-graphics", "entisium-window-glfw", "entisium-rendering")
    add_packages("glfw", "imgui", {public = true})
    add_rules("utils.bin2obj", {extensions = {".ttf"}})
    add_files("fonts/Cousine-Regular.ttf", {zeroend = true})

target("entisium-imgui-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_includedirs("../rendering/tests")
    add_deps("entisium-imgui")
