target("entisium-graphics-opengl")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-graphics", "entisium-profiling")
    add_packages("glad")

target("entisium-graphics-opengl-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-graphics-opengl")
    add_packages("glad")
