target("fei-graphics-opengl")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-profiling")
    add_packages("glad")

target("fei-graphics-opengl-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-graphics-opengl")
    add_packages("glad")
