target("tests")
    set_kind("binary")
    add_files("**.cpp")
    add_packages("catch2")
    add_deps(
        "fei-base",
        "fei-refl",
        "fei-ecs",
        "fei-app",
        "fei-asset",
        "fei-core",
        "fei-math"
    )
