target("fei-ui")
    set_kind("static")
    add_headerfiles("**.hpp")
    add_files("**.cpp")
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math")
    add_packages("glfw", "glad", "imgui") 
    add_rules("utils.bin2obj", {extensions = {".ttf"}})
    add_files("fonts/Cousine-Regular.ttf", {zeroend = true})
