target("fei-scripting")
    set_kind("static")
    add_rules("fei.reflect")
    add_files("*.cpp")
    add_headerfiles("**.hpp")
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math", "fei-core")
    add_packages("lua")

target("fei-scripting-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_packages("lua")
    add_deps("fei-scripting")
