target("fei-graphics-opengl-glfw")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-graphics-opengl", "fei-window", "fei-profiling")
    add_packages("glfw", "glad")
