add_requires("vulkansdk", "vulkan-validationlayers")

target("fei-graphics-vulkan")
    set_kind("static")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics")
    add_packages("vulkansdk", {public = true})
    add_packages("vulkan-validationlayers", {public = true})
