target("entisium-snapshot")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-ecs", "entisium-serialization")

target("entisium-snapshot-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-snapshot")

target("entisium-snapshot-runtime")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("runtime/include/**.hpp")
    add_files("runtime/src/*.cpp")
    add_includedirs("runtime/include", {public = true})
    add_deps("entisium-snapshot", "entisium-core", "entisium-input")

target("entisium-snapshot-runtime-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("runtime/tests/*.cpp")
    add_deps("entisium-snapshot-runtime")

target("entisium-snapshot-runtime-luau")
    set_kind("static")
    add_headerfiles("runtime_luau/include/**.hpp")
    add_files("runtime_luau/src/*.cpp")
    add_includedirs("runtime_luau/include", {public = true})
    add_deps("entisium-snapshot", "entisium-scripting-luau")

target("entisium-snapshot-runtime-luau-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("runtime_luau/tests/*.cpp")
    add_deps("entisium-snapshot-runtime-luau", "entisium-scripting-luau")

target("entisium-snapshot-runtime-asset")
    set_kind("static")
    add_headerfiles("runtime_asset/include/**.hpp")
    add_files("runtime_asset/src/*.cpp")
    add_includedirs("runtime_asset/include", {public = true})
    add_deps("entisium-snapshot", "entisium-asset")

target("entisium-snapshot-runtime-asset-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("runtime_asset/tests/*.cpp")
    add_deps("entisium-snapshot-runtime-asset")

target("entisium-snapshot-runtime-physics2d")
    set_kind("static")
    add_headerfiles("runtime_physics2d/include/**.hpp")
    add_files("runtime_physics2d/src/*.cpp")
    add_includedirs("runtime_physics2d/include", {public = true})
    add_deps("entisium-snapshot", "entisium-physics2d")

target("entisium-snapshot-runtime-physics2d-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("runtime_physics2d/tests/*.cpp")
    add_deps("entisium-snapshot-runtime-physics2d", "entisium-snapshot-runtime")

target("entisium-snapshot-runtime-rendering")
    set_kind("static")
    add_headerfiles("runtime_rendering/include/**.hpp")
    add_files("runtime_rendering/src/*.cpp")
    add_includedirs("runtime_rendering/include", {public = true})
    add_deps("entisium-snapshot", "entisium-rendering")

target("entisium-snapshot-runtime-rendering-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("runtime_rendering/tests/*.cpp")
    add_deps("entisium-snapshot-runtime-rendering")

target("entisium-snapshot-runtime-ui")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("runtime_ui/include/**.hpp")
    add_files("runtime_ui/src/*.cpp")
    add_includedirs("runtime_ui/include", {public = true})
    add_deps("entisium-snapshot", "entisium-ui-widgets")

target("entisium-snapshot-runtime-ui-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("runtime_ui/tests/*.cpp")
    add_deps(
        "entisium-snapshot-runtime-ui",
        "entisium-snapshot-runtime",
        "entisium-snapshot-runtime-asset"
    )
