target("fei-snapshot")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-ecs", "fei-serialization")

target("fei-snapshot-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-snapshot")

target("fei-snapshot-runtime")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("runtime/include/**.hpp")
    add_files("runtime/src/*.cpp")
    add_includedirs("runtime/include", {public = true})
    add_deps("fei-snapshot", "fei-core", "fei-window")

target("fei-snapshot-runtime-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("runtime/tests/*.cpp")
    add_deps("fei-snapshot-runtime")

target("fei-snapshot-runtime-luau")
    set_kind("static")
    add_headerfiles("runtime_luau/include/**.hpp")
    add_files("runtime_luau/src/*.cpp")
    add_includedirs("runtime_luau/include", {public = true})
    add_deps("fei-snapshot", "fei-scripting-luau")

target("fei-snapshot-runtime-luau-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("runtime_luau/tests/*.cpp")
    add_deps("fei-snapshot-runtime-luau", "fei-scripting-luau")

target("fei-snapshot-runtime-asset")
    set_kind("static")
    add_headerfiles("runtime_asset/include/**.hpp")
    add_files("runtime_asset/src/*.cpp")
    add_includedirs("runtime_asset/include", {public = true})
    add_deps("fei-snapshot", "fei-asset")

target("fei-snapshot-runtime-asset-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("runtime_asset/tests/*.cpp")
    add_deps("fei-snapshot-runtime-asset")

target("fei-snapshot-runtime-physics2d")
    set_kind("static")
    add_headerfiles("runtime_physics2d/include/**.hpp")
    add_files("runtime_physics2d/src/*.cpp")
    add_includedirs("runtime_physics2d/include", {public = true})
    add_deps("fei-snapshot", "fei-physics2d")

target("fei-snapshot-runtime-physics2d-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("runtime_physics2d/tests/*.cpp")
    add_deps("fei-snapshot-runtime-physics2d", "fei-snapshot-runtime")

target("fei-snapshot-runtime-rendering")
    set_kind("static")
    add_headerfiles("runtime_rendering/include/**.hpp")
    add_files("runtime_rendering/src/*.cpp")
    add_includedirs("runtime_rendering/include", {public = true})
    add_deps("fei-snapshot", "fei-rendering")

target("fei-snapshot-runtime-rendering-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("runtime_rendering/tests/*.cpp")
    add_deps("fei-snapshot-runtime-rendering")

target("fei-snapshot-runtime-ui")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("runtime_ui/include/**.hpp")
    add_files("runtime_ui/src/*.cpp")
    add_includedirs("runtime_ui/include", {public = true})
    add_deps("fei-snapshot", "fei-ui-widgets")

target("fei-snapshot-runtime-ui-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("runtime_ui/tests/*.cpp")
    add_deps(
        "fei-snapshot-runtime-ui",
        "fei-snapshot-runtime",
        "fei-snapshot-runtime-asset"
    )
