target("fei-graphics-opengl-glfw")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-graphics-opengl", "fei-window", "fei-profiling")
    add_packages("glfw", "glad")

target("fei-graphics-opengl-glfw-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-graphics-opengl-glfw")
