target("entisium-graphics-opengl-glfw")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-graphics", "entisium-graphics-opengl", "entisium-shader-opengl", "entisium-window-glfw", "entisium-profiling")
    add_packages("glfw", "glad")

target("entisium-graphics-opengl-glfw-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-graphics-opengl-glfw")
