target("fei-graphics-vulkan-glfw")
    set_kind("static")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-graphics-vulkan", "fei-window", "fei-profiling")
    add_packages("glfw", "vulkansdk")
