target("entisium-runtime-inspection-playtest")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-runtime-inspection", "entisium-playtest")
    add_packages("nlohmann_json")

target("entisium-runtime-inspection-playtest-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.test.cpp")
    add_deps("entisium-runtime-inspection-playtest")
    add_packages("nlohmann_json")
