target("entisium-ui-widgets")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base", "entisium-refl", "entisium-ecs", "entisium-app", "entisium-window", "entisium-input", "entisium-input-focus", "entisium-ui")

target("entisium-ui-widgets-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("tests/*.cpp")
    add_deps("entisium-ui-widgets")
