target("entisium-devtools-reflection")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp", "src/*.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-devtools")

target("entisium-devtools-reflection-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("tests/*.cpp")
    add_includedirs("src")
    add_deps("entisium-devtools-reflection")
