target("entisium-runtime-protocol")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-app", "entisium-base")
    add_packages("cpp-httplib", "nlohmann_json")
    if is_plat("windows") then
        add_syslinks("ws2_32")
    end

target("entisium-runtime-protocol-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.test.cpp")
    add_deps("entisium-runtime-protocol")

target("entisium-runtime-probe-fixture")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.reflect")
    add_files("tests/probe_fixture.cpp")
    add_deps("entisium-runtime-protocol", "entisium-runtime-inspection-ecs")
