// Generated by reflgen
#include "refl/type.hpp"
#include "refl/registry.hpp"

struct A {};

void register_classes() {
    using namespace fei;
    auto& registry = Registry::instance();
    registry.register_cls<A>();
}
