target("fei-ecs")
    set_kind("static")
    add_headerfiles("**.hpp")
    add_files("*.cpp")
    add_deps("fei-base", "fei-refl")

target("fei-ecs-tests")
    set_kind("binary")
    set_default(false)
    add_files("tests/*.cpp")
    add_packages("catch2")
    add_deps("fei-ecs")
    add_tests("default")
