target("fei-text")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-asset", "fei-math", "fei-core")
    add_packages("stb")

target("fei-text-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("tests/*.cpp")
    add_rules("utils.bin2obj", {extensions = {".ttf"}})
    add_files("../imgui/fonts/Cousine-Regular.ttf", {zeroend = true})
    add_deps("fei-text")
