target("entisium-refl")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base")

target("entisium-refl-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_rules("entisium.reflect")
    add_files("tests/*.cpp")
    add_headerfiles("tests/*.hpp")
    add_deps("entisium-refl")
