target("entisium-input")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp", "include/**.def")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base", "entisium-refl", "entisium-ecs", "entisium-app", "entisium-math")

target("entisium-input-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.test.cpp")
    add_deps("entisium-input")
