namespace fei.pbr.forward_io {
struct VertexOutput {
    float4 position : SV_Position;
    [vk::location(0)] float3 position_ws : POSITION_WS;
    [vk::location(1)] float3 normal_ws : NORMAL_WS;
#ifdef VERTEX_UVS
    [vk::location(2)] float2 tex_coords : TEXCOORD0;
#endif
#ifdef VERTEX_TANGENTS
    [vk::location(3)] float3 tangent_ws : TANGENT_WS;
#endif
};

struct FragmentOutput {
    [vk::location(0)] float4 color : SV_Target0;
};
} // namespace fei.pbr.forward_io
