target("fei-physics2d")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-app", "fei-core", "fei-ecs", "fei-math")
    add_packages("box2d", {public = false})

target("fei-physics2d-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test", "fei.reflect")
    add_files("tests/*.cpp")
    add_deps("fei-physics2d")
