target("entisium-physics2d")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-app", "entisium-core", "entisium-ecs", "entisium-math")
    add_packages("box2d", {public = false})

target("entisium-physics2d-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test", "entisium.reflect")
    add_files("tests/*.cpp")
    add_deps("entisium-physics2d")
