name: Luau Scripting Sample
asset_directory: assets

runtime:
  plugins:
    - OpenGLGlfw
    - Rendering
    - Sprite
    - project_runtime::LuauScripts

scripts:
  - project://scripts/movement.luau
