target("fei-core")
    set_kind("static")
    add_headerfiles("**.hpp")
    add_files("*.cpp")
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-asset")
    add_packages("stb")

target("fei-core-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-core", "fei-graphics")
