add_requires("vulkansdk", "vulkan-validationlayers")

target("fei-graphics-vulkan")
    set_kind("static")
    add_rules("fei.reflect")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-graphics", "fei-profiling")
    add_packages("vulkansdk", {public = true})
    add_packages("vulkan-validationlayers", {public = true})

target("fei-graphics-vulkan-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-graphics-vulkan")
