add_requires("vulkansdk", "vulkan-validationlayers")

target("entisium-graphics-vulkan")
    set_kind("static")
    add_rules("entisium.reflect")
    set_default(false)
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-graphics", "entisium-profiling")
    add_packages("vulkansdk", {public = true})
    add_packages("vulkan-validationlayers", {public = true})

target("entisium-graphics-vulkan-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-graphics-vulkan")
