target("fei-math")
    set_kind("static")
    add_headerfiles("**.hpp")
    add_files("*.cpp")

target("fei-math-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-math")
