target("entisium-scene")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base", "entisium-refl", "entisium-serialization", "entisium-ecs", "entisium-app", "entisium-math", "entisium-asset", "entisium-graphics", "entisium-window", "entisium-rendering", "entisium-pbr")
    add_packages("tinyobjloader")
    add_packages("yaml-cpp", {public = true})

target("entisium-scene-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-scene")
