target("entisium-runtime-inspection-profiling")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-runtime-inspection", "entisium-profiling", "entisium-ecs")
    add_packages("nlohmann_json")

target("entisium-runtime-inspection-profiling-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.test.cpp")
    add_deps("entisium-runtime-inspection-profiling")
    add_packages("nlohmann_json")
