target("entisium-pbr")
    set_kind("static")
    add_rules("entisium.reflect")
    add_shader_source("pbr", path.join(os.scriptdir(), "shaders"))
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp", "src/passes/*.cpp")
    add_includedirs("include", {public = true})
    add_includedirs("../scene/include")
    add_deps("entisium-base", "entisium-refl", "entisium-ecs", "entisium-app", "entisium-math", "entisium-asset", "entisium-graphics", "entisium-window", "entisium-rendering")
    add_rules("utils.bin2obj", {extensions = {".png"}})
    add_files("luts/*.png", {zeroend = true})

target("entisium-pbr-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_includedirs("../rendering/tests")
    add_deps("entisium-pbr", "entisium-shader-opengl")
