#include "codegen.hpp"

#include <algorithm>
#include <fstream>
#include <set>
#include <stdexcept>

namespace fei::reflgen {
namespace {

[[nodiscard]] std::filesystem::path
normalized_absolute_path(const std::filesystem::path& path) {
    std::error_code error;
    auto absolute = std::filesystem::absolute(path, error);
    if (error) {
        absolute = path;
    }
    return absolute.lexically_normal();
}

[[nodiscard]] std::string include_path_for(
    const std::string& source_file,
    const std::filesystem::path& root_dir
) {
    const auto source = normalized_absolute_path(source_file);
    const auto root = normalized_absolute_path(root_dir);

    std::error_code error;
    auto relative = std::filesystem::relative(source, root, error);
    if (error) {
        relative = source.lexically_relative(root);
    }
    return relative.generic_string();
}

[[nodiscard]] std::vector<ClassInfo>
sorted_classes(const std::vector<ClassInfo>& classes) {
    auto sorted = classes;
    std::ranges::sort(sorted, {}, &ClassInfo::name);
    return sorted;
}

[[nodiscard]] std::vector<EnumInfo>
sorted_enums(const std::vector<EnumInfo>& enums) {
    auto sorted = enums;
    std::ranges::sort(sorted, {}, &EnumInfo::name);
    return sorted;
}

[[nodiscard]] std::string
joined_param_types(const std::vector<ParamInfo>& parameters) {
    std::string result;
    for (const auto& param : parameters) {
        if (!result.empty()) {
            result += ", ";
        }
        result += param.type_name;
    }
    return result;
}

} // namespace

void generate_cpp_file(
    const ParseResult& result,
    const std::filesystem::path& root_dir,
    const std::filesystem::path& output_file,
    const std::string& function_name
) {
    if (output_file.has_parent_path()) {
        std::filesystem::create_directories(output_file.parent_path());
    }

    std::ofstream out(output_file, std::ios::binary);
    if (!out) {
        throw std::runtime_error(
            "failed to open output file: " + output_file.string()
        );
    }

    out << "// This file is generated by fei-reflgen\n\n";
    out << "#include \"refl/registry.hpp\"\n";
    out << "#include \"refl/cls.hpp\"\n";
    out << "#include \"refl/enum.hpp\"\n\n";
    out << "#include <cstdint>\n\n";

    std::set<std::string> includes;
    for (const auto& cls : result.classes) {
        includes.insert(include_path_for(cls.source_file, root_dir));
    }
    for (const auto& enum_info : result.enums) {
        includes.insert(include_path_for(enum_info.source_file, root_dir));
    }
    for (const auto& include : includes) {
        out << "#include \"" << include << "\"\n";
    }

    out << "\nnamespace fei::refl::generated {\n";
    out << "void " << function_name << "(Registry& registry) {\n\n";

    for (const auto& cls : sorted_classes(result.classes)) {
        if (cls.name == "fei::Registry") {
            continue;
        }

        out << "registry.register_cls<" << cls.name << ">()\n";
        for (const auto& prop : cls.properties) {
            if (prop.access == "public") {
                out << "    .add_property(\"" << prop.name << "\", &"
                    << cls.name << "::" << prop.name << ")\n";
            }
        }
        for (const auto& method : cls.methods) {
            if (method.access == "public") {
                out << "    .add_method(\"" << method.name << "\", static_cast<"
                    << method.to_cpp_type(cls.name) << ">(&" << cls.name
                    << "::" << method.name << "))\n";
            }
        }
        if (!cls.is_abstract()) {
            for (const auto& constructor : cls.constructors) {
                if (constructor.access != "public") {
                    continue;
                }
                if (constructor.parameters.empty()) {
                    out << "    .add_constructor<" << cls.name << ">()\n";
                } else {
                    out << "    .add_constructor<" << cls.name << ", "
                        << joined_param_types(constructor.parameters)
                        << ">()\n";
                }
            }
        }
        out << "    ;\n";
    }

    out << "\n";

    for (const auto& enum_info : sorted_enums(result.enums)) {
        out << "registry.register_enum<" << enum_info.name << ">()\n";
        for (const auto& enum_value : enum_info.values) {
            out << "    .add_enumerator(\"" << enum_value.name
                << "\", static_cast<std::int64_t>(" << enum_info.name
                << "::" << enum_value.name << "))\n";
        }
        out << "    ;\n";
    }

    out << "\n}\n";
    out << "} // namespace fei::refl::generated\n";
}

void generate_aggregate_cpp_file(
    const std::vector<std::string>& function_names,
    const std::filesystem::path& output_file
) {
    if (output_file.has_parent_path()) {
        std::filesystem::create_directories(output_file.parent_path());
    }

    std::ofstream out(output_file, std::ios::binary);
    if (!out) {
        throw std::runtime_error(
            "failed to open output file: " + output_file.string()
        );
    }

    out << "// This file is generated by fei-reflgen\n\n";
    out << "#include \"refl/generated.hpp\"\n";
    out << "#include \"refl/registry.hpp\"\n\n";

    out << "namespace fei::refl::generated {\n";
    for (const auto& function_name : function_names) {
        out << "void " << function_name << "(Registry& registry);\n";
    }
    out << "} // namespace fei::refl::generated\n\n";

    out << "namespace fei {\n\n";
    out << "void register_generated_reflection() {\n";
    out << "    auto& registry = Registry::instance();\n";
    for (const auto& function_name : function_names) {
        out << "    refl::generated::" << function_name << "(registry);\n";
    }
    out << "}\n\n";
    out << "} // namespace fei\n";
}

} // namespace fei::reflgen
