#include "codegen.hpp"

#include <algorithm>
#include <fstream>
#include <set>
#include <stdexcept>

namespace fei::reflgen {
namespace {

[[nodiscard]] std::filesystem::path
normalized_absolute_path(const std::filesystem::path& path) {
    std::error_code error;
    auto absolute = std::filesystem::absolute(path, error);
    if (error) {
        absolute = path;
    }
    return absolute.lexically_normal();
}

[[nodiscard]] std::string include_path_for(
    const std::string& source_file,
    const std::filesystem::path& root_dir
) {
    const auto source = normalized_absolute_path(source_file);
    const auto root = normalized_absolute_path(root_dir);

    std::error_code error;
    auto relative = std::filesystem::relative(source, root, error);
    if (error) {
        relative = source.lexically_relative(root);
    }
    return relative.generic_string();
}

[[nodiscard]] std::vector<ClassInfo>
sorted_classes(const std::vector<ClassInfo>& classes) {
    auto sorted = classes;
    std::ranges::sort(sorted, {}, &ClassInfo::name);
    return sorted;
}

[[nodiscard]] std::vector<EnumInfo>
sorted_enums(const std::vector<EnumInfo>& enums) {
    auto sorted = enums;
    std::ranges::sort(sorted, {}, &EnumInfo::name);
    return sorted;
}

[[nodiscard]] std::string
joined_param_types(const std::vector<ParamInfo>& parameters) {
    std::string result;
    for (const auto& param : parameters) {
        if (!result.empty()) {
            result += ", ";
        }
        result += param.type_name;
    }
    return result;
}

[[nodiscard]] bool
has_annotation(const std::vector<ReflectionTag>& tags, std::string_view name) {
    return std::ranges::any_of(tags, [name](const ReflectionTag& tag) {
        return tag.key == name && !tag.value;
    });
}

[[nodiscard]] std::optional<std::string> annotation_value(
    const std::vector<ReflectionTag>& tags,
    std::string_view annotation,
    std::string_view field
) {
    const auto found =
        std::ranges::find_if(tags, [&](const ReflectionTag& tag) {
            return tag.group == annotation && tag.field == field && tag.value;
        });
    if (found == tags.end()) {
        return std::nullopt;
    }
    return found->value;
}

[[nodiscard]] std::string default_plugin_name(std::string_view type_name) {
    constexpr std::string_view c_root_namespace = "fei::";
    constexpr std::string_view c_plugin_suffix = "Plugin";
    std::string name(
        type_name.starts_with(c_root_namespace) ?
            type_name.substr(c_root_namespace.size()) :
            type_name
    );
    const auto namespace_end = name.rfind("::");
    const auto local_name_start =
        namespace_end == std::string::npos ? 0 : namespace_end + 2;
    if (name.size() - local_name_start > c_plugin_suffix.size() &&
        name.ends_with(c_plugin_suffix)) {
        name.erase(name.size() - c_plugin_suffix.size());
    }
    return name;
}

[[nodiscard]] std::optional<std::string> plugin_name(const ClassInfo& cls) {
    if (!has_annotation(cls.tags, "Plugin")) {
        return std::nullopt;
    }
    for (const auto& tag : cls.tags) {
        if (tag.group == "Plugin" && tag.field != "name") {
            throw std::runtime_error(
                "Unknown Plugin annotation field '" + *tag.field +
                "' on class " + cls.name
            );
        }
    }
    if (auto explicit_name = annotation_value(cls.tags, "Plugin", "name")) {
        return explicit_name;
    }
    return default_plugin_name(cls.name);
}

[[nodiscard]] bool is_plugin_lifecycle_method(std::string_view name) {
    return name == "dependencies" || name == "setup" || name == "finish" ||
           name == "cleanup";
}

} // namespace

void generate_cpp_file(
    const ParseResult& result,
    const std::filesystem::path& root_dir,
    const std::filesystem::path& output_file,
    const std::string& function_name
) {
    if (output_file.has_parent_path()) {
        std::filesystem::create_directories(output_file.parent_path());
    }

    std::ofstream out(output_file, std::ios::binary);
    if (!out) {
        throw std::runtime_error(
            "failed to open output file: " + output_file.string()
        );
    }

    out << "// This file is generated by fei-reflgen\n\n";
    out << "#include \"refl/registry.hpp\"\n";
    out << "#include \"refl/cls.hpp\"\n";
    out << "#include \"refl/enum.hpp\"\n";
    if (std::ranges::any_of(result.classes, [](const ClassInfo& cls) {
            return has_annotation(cls.tags, "Plugin");
        })) {
        out << "#include \"app/plugin_registry.hpp\"\n";
    }
    out << "\n";
    out << "#include <cstdint>\n\n";

    std::set<std::string> includes;
    for (const auto& cls : result.classes) {
        includes.insert(include_path_for(cls.source_file, root_dir));
    }
    for (const auto& enum_info : result.enums) {
        includes.insert(include_path_for(enum_info.source_file, root_dir));
    }
    for (const auto& include : includes) {
        out << "#include \"" << include << "\"\n";
    }

    out << "\nnamespace fei::refl::generated {\n";
    out << "void " << function_name << "(Registry& registry) {\n\n";

    for (const auto& cls : sorted_classes(result.classes)) {
        if (cls.name == "fei::Registry") {
            continue;
        }
        const auto generated_plugin_name = plugin_name(cls);

        out << "registry.register_cls<" << cls.name << ">()\n";
        for (const auto& prop : cls.properties) {
            if (prop.access == "public") {
                out << "    .add_property(\"" << prop.name << "\", &"
                    << cls.name << "::" << prop.name << ")\n";
            }
        }
        for (const auto& method : cls.methods) {
            if (method.access == "public" &&
                !(generated_plugin_name &&
                  is_plugin_lifecycle_method(method.name))) {
                out << "    .add_method(\"" << method.name << "\", static_cast<"
                    << method.to_cpp_type(cls.name) << ">(&" << cls.name
                    << "::" << method.name << "))\n";
            }
        }
        if (!cls.is_abstract()) {
            for (const auto& constructor : cls.constructors) {
                if (constructor.access != "public") {
                    continue;
                }
                if (constructor.parameters.empty()) {
                    out << "    .add_constructor<" << cls.name << ">()\n";
                } else {
                    out << "    .add_constructor<" << cls.name << ", "
                        << joined_param_types(constructor.parameters)
                        << ">()\n";
                }
            }
        }
        out << "    ;\n";
        for (const auto& tag : cls.tags) {
            if (tag.group && tag.field && tag.value) {
                out << "registry.add_generated_annotation_field<" << cls.name
                    << ">(\"" << *tag.group << "\", \"" << *tag.field
                    << "\", \"" << *tag.value << "\");\n";
            } else {
                out << "registry.add_generated_annotation<" << cls.name
                    << ">(\"" << tag.key << "\");\n";
            }
        }
        if (generated_plugin_name) {
            out << "register_generated_plugin<" << cls.name << ">(\""
                << *generated_plugin_name << "\");\n";
        }
    }

    out << "\n";

    for (const auto& enum_info : sorted_enums(result.enums)) {
        if (has_annotation(enum_info.tags, "Plugin")) {
            throw std::runtime_error(
                "Plugin annotation can only be applied to classes: " +
                enum_info.name
            );
        }
        out << "registry.register_enum<" << enum_info.name << ">()\n";
        for (const auto& enum_value : enum_info.values) {
            out << "    .add_enumerator(\"" << enum_value.name
                << "\", static_cast<std::int64_t>(" << enum_info.name
                << "::" << enum_value.name << "))\n";
        }
        out << "    ;\n";
        for (const auto& tag : enum_info.tags) {
            if (tag.group && tag.field && tag.value) {
                out << "registry.add_generated_annotation_field<"
                    << enum_info.name << ">(\"" << *tag.group << "\", \""
                    << *tag.field << "\", \"" << *tag.value << "\");\n";
            } else {
                out << "registry.add_generated_annotation<" << enum_info.name
                    << ">(\"" << tag.key << "\");\n";
            }
        }
    }

    out << "\n}\n";
    out << "} // namespace fei::refl::generated\n";
}

void generate_aggregate_cpp_file(
    const std::vector<std::string>& function_names,
    const std::filesystem::path& output_file
) {
    if (output_file.has_parent_path()) {
        std::filesystem::create_directories(output_file.parent_path());
    }

    std::ofstream out(output_file, std::ios::binary);
    if (!out) {
        throw std::runtime_error(
            "failed to open output file: " + output_file.string()
        );
    }

    out << "// This file is generated by fei-reflgen\n\n";
    out << "#include \"refl/generated.hpp\"\n";
    out << "#include \"refl/registry.hpp\"\n\n";

    out << "namespace fei::refl::generated {\n";
    for (const auto& function_name : function_names) {
        out << "void " << function_name << "(Registry& registry);\n";
    }
    out << "} // namespace fei::refl::generated\n\n";

    out << "namespace fei {\n\n";
    out << "void register_generated_reflection() {\n";
    out << "    auto& registry = Registry::instance();\n";
    for (const auto& function_name : function_names) {
        out << "    refl::generated::" << function_name << "(registry);\n";
    }
    out << "}\n\n";
    out << "} // namespace fei\n";
}

} // namespace fei::reflgen
