target("fei-imgui")
    set_kind("static")
    add_rules("fei.reflect")
    add_shader_source("imgui", path.join(os.scriptdir(), "shaders"))
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math", "fei-asset", "fei-graphics", "fei-window", "fei-rendering")
    add_packages("glfw", "imgui", {public = true})
    add_rules("utils.bin2obj", {extensions = {".ttf"}})
    add_files("fonts/Cousine-Regular.ttf", {zeroend = true})

target("fei-imgui-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_includedirs("../rendering/tests")
    add_deps("fei-imgui")
