target("fei-rendering")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp", "src/mesh/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math", "fei-asset", "fei-core", "fei-graphics", "fei-profiling")
    add_packages("tinyobjloader", "mikktspace", "nlohmann_json")

target("fei-rendering-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-rendering")
