target("fei-window")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("include/**.hpp", "include/**.def")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math")
    add_packages("glfw")
