add_includedirs(".", {public = true})

includes("base")
includes("refl")
includes("ecs")
includes("app")
includes("window")
includes("math")
includes("graphics")
includes("render2d")
includes("core")
