add_includedirs(".", {public = true})

includes("app")
includes("asset")
includes("base")
includes("refl")
includes("ecs")
includes("task")
includes("window")
includes("math")
includes("graphics")
includes("graphics_opengl")
includes("graphics_vulkan")
includes("core")
includes("scripting")
includes("rendering")
includes("ui")
includes("pbr")
includes("scene")
includes("web_preview")
