target("fei-gltf")
    set_kind("static")
    add_rules("fei.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("fei-base", "fei-app", "fei-asset", "fei-core", "fei-math", "fei-rendering", "fei-pbr", "fei-scene")
    add_packages("fastgltf")

target("fei-gltf-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-gltf")
