target("entisium-gltf")
    set_kind("static")
    add_rules("entisium.reflect")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base", "entisium-app", "entisium-asset", "entisium-core", "entisium-math", "entisium-rendering", "entisium-pbr", "entisium-scene")
    add_packages("fastgltf")

target("entisium-gltf-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-gltf")
