target("fei-pbr")
    set_kind("static")
    add_headerfiles("include/**.hpp")
    add_files("src/*.cpp", "src/passes/*.cpp")
    add_includedirs("include", {public = true})
    add_includedirs("../scene/include")
    add_deps("fei-base", "fei-refl", "fei-ecs", "fei-app", "fei-math", "fei-asset", "fei-graphics", "fei-window", "fei-rendering")
    add_rules("fei.shader")
    set_values("fei.shader.source_root", path.join(os.scriptdir(), "shaders"))
    add_files("shaders/*.vert")
    add_files("shaders/*.geom")
    add_files("shaders/*.frag")
    add_files("shaders/*.comp")
    add_rules("utils.bin2obj", {extensions = {".png"}})
    add_files("luts/*.png", {zeroend = true})

target("fei-pbr-tests")
    set_kind("binary")
    set_default(false)
    add_rules("fei.test")
    add_files("tests/*.cpp")
    add_deps("fei-pbr")
